### ISSUE TITLE
Undefined name 'testname' in cleartestresult()

### ISSUE THREAD

**Issue by cclauss** [CERTCC/tapioca#1]
https://github.com/CERTCC/tapioca/blob/master/tapioca.py#L831-L838

flake8 testing of https://github.com/CERTCC/tapioca on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./net.py:451:24: F821 undefined name 'dtlshostt'
                      (dtlshostt, color.bright(negotiated_ciphersuite)))
                       ^
./tapioca.py:833:12: F821 undefined name 'testname'
        if testname == 'tcpdump':
           ^
./tapioca.py:835:14: F821 undefined name 'testname'
        elif testname == 'ssltest':
             ^
./tapioca.py:837:14: F821 undefined name 'testname'
        elif testname == 'full':
             ^
4     F821 undefined name 'dtlshostt'
4
```

**Comment by wdormann** [comment]
Thanks.   The first was a typo, fixed in a77e9b5f01bbad82d25f4fd3dd2f0d207ff8bb79
The second 3 were in an unused function, removed in ceb1b1a2496b6ce163d3a0304729c02716380465
